services:
  backend:
    build: ./docker/lambda-backend
    container_name: lambda-backend
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - $PWD:$PWD
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: $PWD/lambda-backend
    command: ['/bin/bash', "$PWD/docker/lambda-backend/entrypoint.sh"]
    ports:
      - 3000:3001
    networks:
      - backend
    tty: true
  
  frontend:
    build: ./docker/react-frontend
    container_name: react-frontend
    volumes:
      - ./react-frontend:/react-frontend
      - ./docker/react-frontend:/docker/react-frontend
    working_dir: /react-frontend
    command: ['/bin/bash', "/docker/react-frontend/entrypoint.sh"]
    ports:
      - 5173:5173
    tty: true

networks:
  backend:
    name: backend_network
    driver: bridge